# Docker Compose configuration for Folksonomy API

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - POSTGRES_USER=folksonomy
      - POSTGRES_PASSWORD=folksonomy
      - POSTGRES_DATABASE=folksonomy
      - POSTGRES_HOST=db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=folksonomy
      - POSTGRES_PASSWORD=folksonomy
      - POSTGRES_DB=folksonomy
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_data: