# Docker Compose configuration for Folksonomy API
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount specific files instead of the entire directory
      - ./local_settings.py:/app/local_settings.py
      # Mount a volume for logs
      - api_logs:/app/logs
    environment:
      - POSTGRES_USER=folksonomy
      - POSTGRES_PASSWORD=folksonomy
      - POSTGRES_DATABASE=folksonomy
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy  # Wait for DB to be fully ready
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=folksonomy
      - POSTGRES_PASSWORD=folksonomy
      - POSTGRES_DB=folksonomy
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U folksonomy -d folksonomy"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  api_logs: