# Docker Compose configuration for Folksonomy API
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount .env file for environment variables
      - ./.env:/app/.env
      # Mount a volume for logs
      - api_logs:/app/logs
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy  # Wait for DB to be fully ready
    restart: unless-stopped

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-folksonomy}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-folksonomy}
      - POSTGRES_DB=${POSTGRES_DATABASE:-folksonomy}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-folksonomy} -d ${POSTGRES_DATABASE:-folksonomy}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  api_logs: